## Projet Stats en Gde dimension : Partie 3 : Datachallenge
## Cas particulier des Réseaux de neurones.

Kévin Jousselin

# I - Importation des données

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
from google.colab import files
#files.upload()


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
import plotly.express as px
import pandas as pd

import matplotlib.pyplot as plt

In [ ]:
# importer les données
dossier = '/content/drive/MyDrive/M2 DS/DataChallenge/'

df_train = pd.read_csv(dossier+'mon_df_train.csv',index_col=0)
df_valid = pd.read_csv(dossier+'mon_df_valid.csv',index_col=0)

for TYPE in ['valid', 'train']:
    for j in range(1,3):
        for k in range(10):
            exec(f'Y_{TYPE}_{j}_{k} = np.fromfile(dossier+f"Y_{TYPE}_{j}_{k}.np")')


In [ ]:
df_train.head(2)

t_slp_begin  slp0_x_0_y_0  slp0_x_0_y_4  slp0_x_0_y_8  slp0_x_0_y_12  \
0 -630892800.0      1.017251      1.019911      1.021260       1.021208   
1 -630806400.0      1.014756      1.017956      1.020477       1.020881   

   slp0_x_0_y_16  slp0_x_0_y_20  slp0_x_0_y_24  slp0_x_0_y_28  slp0_x_0_y_32  \
0       1.019921       1.018681       1.018545       1.017563       1.015939   
1       1.019801       1.019044       1.018436       1.017728       1.015910   

   ...  surge2_input_2  surge2_input_3  surge2_input_4  surge2_input_5  \
0  ...       -0.757999       -0.129327       -0.179620       -0.372413   
1  ...       -0.179620       -0.372413       -0.053886        0.356847   

   surge2_input_6  surge2_input_7  surge2_input_8  surge2_input_9  \
0       -0.053886        0.356847        0.348464        0.264641   
1        0.348464        0.264641        0.901696        0.449052   

   t_surge1_output  t_surge2_output  
0     -630486000.0     -630482400.0  
1     -630399600.0     -630392400.0  

[2 rows x 1125 columns]

In [ ]:
print(df_train.shape)
print(Y_train_1_0)
print(len(Y_train_1_0))
df_train.head(3)

(3386, 1125)
[ 0.07077463 -0.35489084 -0.77385293 ...  1.45167365  1.44832196
  1.66283054]
3386


t_slp_begin  slp0_x_0_y_0  slp0_x_0_y_4  slp0_x_0_y_8  slp0_x_0_y_12  \
0 -630892800.0      1.017251      1.019911      1.021260       1.021208   
1 -630806400.0      1.014756      1.017956      1.020477       1.020881   
2 -630720000.0      1.011215      1.013787      1.017968       1.019858   

   slp0_x_0_y_16  slp0_x_0_y_20  slp0_x_0_y_24  slp0_x_0_y_28  slp0_x_0_y_32  \
0       1.019921       1.018681       1.018545       1.017563       1.015939   
1       1.019801       1.019044       1.018436       1.017728       1.015910   
2       1.020021       1.019869       1.019770       1.019589       1.018909   

   ...  surge2_input_2  surge2_input_3  surge2_input_4  surge2_input_5  \
0  ...       -0.757999       -0.129327       -0.179620       -0.372413   
1  ...       -0.179620       -0.372413       -0.053886        0.356847   
2  ...       -0.053886        0.356847        0.348464        0.264641   

   surge2_input_6  surge2_input_7  surge2_input_8  surge2_input_9  \
0       -0.053886        0.356847        0.348464        0.264641   
1        0.348464        0.264641        0.901696        0.449052   
2        0.901696        0.449052        0.113760       -0.422707   

   t_surge1_output  t_surge2_output  
0     -630486000.0     -630482400.0  
1     -630399600.0     -630392400.0  
2     -630309600.0     -630302400.0  

[3 rows x 1125 columns]

# II - Normalisation de la sortie avec StandartScaler


In [ ]:
# Normalisation de la sortie avec MinMaxScaler

from sklearn.preprocessing import MinMaxScaler, StandardScaler

"""
norm_sortie = MinMaxScaler(feature_range = (0, 1))

#Y = np.array(Y_train_1_0).reshape(-1, 1)
#Y = norm_sortie.fit_transform(Y)
# norm_sortie.inverse_transform(Y)

norm_entree = MinMaxScaler(feature_range = (0, 1))  

df_scale = norm_entree.fit_transform(df_train)
df_scale_valid = norm_entree_test.fit_transform(df_valid)
"""

norme_entree = StandardScaler()
df_scale = norm_entree.fit_transform(df_train)
df_scale_valid = norm_entree.fit_transform(df_valid)



In [ ]:
pd.DataFrame(df_scale)

0         1         2         3         4         5         6     \
0    -1.537358 -0.880012 -0.260496  0.222862  0.538409  0.723986  0.852362   
1    -1.537208 -1.378734 -0.668960  0.051775  0.462966  0.694280  0.942041   
2    -1.537057 -2.086704 -1.539697 -0.496059  0.226204  0.748907  1.145302   
3    -1.536888 -3.407726 -3.580782 -3.393518 -2.271157 -0.939173  0.349213   
4    -1.532989  1.101460  1.100986  1.113155  1.146902  1.140368  1.190202   
...        ...       ...       ...       ...       ...       ...       ...   
3381  1.807854 -2.112253 -1.779816 -1.975571 -2.371007 -1.574761 -0.888467   
3382  1.808024 -2.041324 -1.693315 -1.202641 -1.131025 -0.713164 -0.254730   
3383  1.808325 -1.435109 -1.297886 -0.949199 -0.573359 -0.434048 -0.308971   
3384  1.808777  0.141121 -0.231314 -0.610889 -0.460646  0.079402  0.435515   
3385  1.808947  0.632566  0.489252  0.234459  0.007140  0.088473  0.028623   

          7         8         9     ...      1115      1116      1117  \
0     0.874274  0.675420  0.365671  ... -0.763788 -0.133286 -0.179173   
1     0.852672  0.705979  0.360350  ... -0.178617 -0.382057 -0.051666   
2     1.118293  1.050123  0.920206  ... -0.051405  0.364257  0.356357   
3     1.039310  1.234681  1.284463  ...  0.355670  0.269895  0.917389   
4     0.984975  0.943572  0.908724  ...  0.686420  0.973318  1.393415   
...        ...       ...       ...  ...       ...       ...       ...   
3381 -0.916445 -1.015847 -1.096079  ...  0.771227  0.227004  0.075842   
3382 -0.369573 -0.467519 -0.574742  ...  0.075806  0.347100  0.024839   
3383 -0.045675  0.215052  0.455312  ...  0.398074  0.467197  0.288353   
3384  0.904737  1.086731  1.169673  ...  0.423516  0.552980  0.772880   
3385  0.276591  0.324044  0.197388  ...  0.771227  0.904692  0.305354   

          1118      1119      1120      1121      1122      1123      1124  
0    -0.372709 -0.042305  0.396277  0.378549  0.295075 -1.537359 -1.537365  
1     0.381859  0.369612  0.301068  0.941536  0.483605 -1.537208 -1.537208  
2     0.286454  0.935999  0.491485  0.139706 -0.407628 -1.537051 -1.537051  
3     0.477264  0.129327 -0.408669 -0.440341 -0.818967 -1.536894 -1.536894  
4     1.899669  1.322171  0.967529  3.082590  1.580508 -1.532989 -1.532995  
...        ...       ...       ...       ...       ...       ...       ...  
3381  0.364513  0.034930  0.673248  0.421199  0.492175  1.807861  1.807861  
3382  0.659402  0.412520  0.500141  0.310308  0.466466  1.808012  1.808018  
3383  0.459918  0.172235  0.283757  0.446790  0.577870  1.808326  1.808325  
3384  0.928271  0.318123 -0.382703 -0.525642 -0.484754  1.808790  1.808784  
3385 -0.398729 -0.540038 -0.486567 -0.482991 -0.390489  1.808947  1.808941  

[3386 rows x 1125 columns]

# III - Recherche d'un modèle de ML efficace
On construit plusieurs modèles avec des fonctions d'activations et configurations différentes, puis on test sur nos données de validation à l'aide d'une fonction et de boucles.

In [ ]:
df_train.shape

(3386, 1125)

In [ ]:
# Entrée : de 5912 à 24414   23095  1125


from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization, Activation
from keras.layers import Conv1D, MaxPooling1D, GlobalAveragePooling1D, Flatten


import time

from google.colab import files

#taille_entree = df_train.shape[1]

def un_model_sequentiel(first_relu = False, FONCT_ACT = 'relu', avec_conv = False, mon_batch = 32, df = df_scale, y_true = Y_train_1_0, verbose = 0, end = False, sup = True):

    
    taille_entree = df.shape[1]
    
    model = Sequential()
    

    if avec_conv:
      # Add 1D convolutional layer with 32 filters, kernel size of 3 and 'relu' activation
      model.add(Conv1D(32, 3, input_shape=(taille_entree, 1))) #, activation='relu'))
      # Add a batch normalization layer
      model.add(BatchNormalization())
      # Add a max pooling layer
      model.add(MaxPooling1D(pool_size=2))
      # Add a dropout layer to reduce overfitting
      model.add(Dropout(0.5))

      model.add(Flatten())

      if first_relu:
          model.add(Dense(512, activation='relu'))
      else:
          model.add(Dense(512, activation=FONCT_ACT))
      
    else:
        if first_relu:
          model.add(Dense(512, input_shape=(taille_entree,), activation='relu'))
        else:
          model.add(Dense(512, input_shape=(taille_entree,), activation=FONCT_ACT))

    model.add(BatchNormalization())
    model.add(Dropout(0.5))
    
    if sup:     # Une couche de neurones supplémentaire
        model.add(Dense(512, activation=FONCT_ACT))
        model.add(BatchNormalization())
        model.add(Dropout(0.5))

    model.add(Dense(256, activation=FONCT_ACT))
    model.add(BatchNormalization())
    model.add(Dropout(0.5))

    model.add(Dense(128, activation=FONCT_ACT))
    model.add(BatchNormalization())
    model.add(Dropout(0.5))

    model.add(Dense(64, activation=FONCT_ACT))
    model.add(BatchNormalization())
    model.add(Dropout(0.5))

    if end:
        model.add(Dense(32, activation='relu'))
    else:
        model.add(Dense(32, activation=FONCT_ACT))

    model.add(BatchNormalization())
    model.add(Dropout(0.5))

    model.add(Dense(1))
    
    model.compile(optimizer='adam', loss='mean_squared_error')
    
    model.fit(df, y_true, epochs=20, batch_size = mon_batch, verbose = verbose)

    return(model)



In [ ]:
def mesure_pred(model, df = df_scale_valid, y_true = Y_valid_1_0, verbose = 0):

  n = df.shape[0]

  prediction = model.predict(df, verbose = verbose)
  taux = prediction/y_true.reshape(n,1)*100

  # ecart moyen MAE
  MAE = np.sum(np.abs(prediction-y_true.reshape(-1,1)))/n
  MSE = np.sum(np.abs(prediction-y_true.reshape(-1,1))**2)/n

  t1=80
  t2=140
  print(f'\t\t\t\tDe {t1}% à {t2}% : {np.sum((t1<taux).reshape(n,)*(taux<t2).reshape(n,))} sur {n}')

  # xx valeurs entre t1 % et t2 % de la bonne valeur sur n !!
  nb_entre_deux_bornes = np.sum((t1<taux).reshape(n,)*(taux<t2).reshape(n,))

  pourc_ok = round(nb_entre_deux_bornes/n*100,1)
  
  return(MAE, MSE, pourc_ok)



In [ ]:
liste_fonct_activation = ['softmax', 'relu', 'tanh', 'softplus', 'selu', 'elu']

# Après quelques tests, j'ai enlevé les fonctions ci-dessous car elles paraissent moins efficace ici : 
# exponential sigmoid softmax softsign


In [ ]:

df_resultats = pd.DataFrame(columns=['fonc_act' , 'first', 'Conv', 'end', 'sup', 'MAE', 'MSE', 'pourc_ok' ])

for fonc in liste_fonct_activation:

    t0 = time.time()

    print(f"\n\nFonction d'activation : {fonc}")

    for first in [True, False]:   

        print(f"\n\tLa première est RELU : {first}")

        for Conv in [False, True]:    #[True, False]
            #Conv = False


            t00 = time.time()

            print(f"\t\tOn commence par une convolution : {Conv}")

            for sup in [False, True]:
                
                print(f'\t\t\tSup : {sup}')
                
                for end in [False, True]:
                    
                    print(f'\t\t\t\tend : {end}')

                    model = un_model_sequentiel(first_relu=first, FONCT_ACT = fonc, avec_conv=Conv, mon_batch=32, df = df_scale, y_true = Y_train_1_0, end=end, sup=sup)

                    res = mesure_pred(model, df = df_scale_valid, y_true = Y_valid_1_0)

                    print(f"\t\t\t\t\t\t(MAE, MSE, pourc_ok) = {res}")

                    df_temp = pd.DataFrame([(fonc, first, Conv, end, sup) + res], columns = ['fonc_act' , 'first', 'Conv', 'end', 'sup', 'MAE', 'MSE', 'pourc_ok' ])

                    df_resultats = df_resultats.append(df_temp, ignore_index=True)           

                    print(f"\t\t\t\t\t\tTemps pour ce modèle : {round((time.time()-t00)//60, 2)} min {round((time.time()-t00)%60, 0)} secondes.")

    # Enregistrement temporaire :
    df_resultats.to_csv(f'Resultats_de_valid_1_0_d_{fonc}.csv', encoding = 'utf-8-sig')
    files.download(f'Resultats_de_valid_1_0_d_{fonc}.csv')

    print(f"Temps pour cette fonction : {round((time.time()-t0)//60, 2)} min {round((time.time()-t0)%60, 0)} secondes.")


df_resultats.to_csv('Resultats_de_valid_1_0_d.csv', encoding = 'utf-8-sig')

files.download('Resultats_de_valid_1_0_d.csv')




Fonction d'activation : softmax

	La première est RELU : True
		On commence par une convolution : False
			Sup : False
				end : False
				De 80% à 140% : 709 sur 2213
						(MAE, MSE, pourc_ok) = (0.37622117406039796, 0.30972153462064683, 32.0)
						Temps pour ce modèle : 0.0 min 14.0 secondes.
				end : True
				De 80% à 140% : 506 sur 2213
						(MAE, MSE, pourc_ok) = (0.4161187632554957, 0.3925615240425649, 22.9)
						Temps pour ce modèle : 0.0 min 28.0 secondes.
			Sup : True
				end : False
				De 80% à 140% : 645 sur 2213
						(MAE, MSE, pourc_ok) = (0.36930616639413694, 0.29735570154885094, 29.1)
						Temps pour ce modèle : 0.0 min 44.0 secondes.
				end : True
				De 80% à 140% : 590 sur 2213
						(MAE, MSE, pourc_ok) = (0.40225629804445606, 0.3647754384183499, 26.7)
						Temps pour ce modèle : 1.0 min 7.0 secondes.
		On commence par une convolution : True
			Sup : False
				end : False
				De 80% à 140% : 669 sur 2213
						(MAE, MSE, pourc_ok) = (0.38760265987157, 0.

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Temps pour cette fonction : 5.0 min 5.0 secondes.


Fonction d'activation : relu

	La première est RELU : True
		On commence par une convolution : False
			Sup : False
				end : False
				De 80% à 140% : 489 sur 2213
						(MAE, MSE, pourc_ok) = (0.38314755365577013, 0.29418416359820737, 22.1)
						Temps pour ce modèle : 0.0 min 22.0 secondes.
				end : True
				De 80% à 140% : 579 sur 2213
						(MAE, MSE, pourc_ok) = (0.3710810395718956, 0.27942181878111516, 26.2)
						Temps pour ce modèle : 0.0 min 36.0 secondes.
			Sup : True
				end : False
				De 80% à 140% : 565 sur 2213
						(MAE, MSE, pourc_ok) = (0.3725651318773038, 0.2845533042687607, 25.5)
						Temps pour ce modèle : 0.0 min 51.0 secondes.
				end : True
				De 80% à 140% : 549 sur 2213
						(MAE, MSE, pourc_ok) = (0.38535249826319184, 0.30206394604770914, 24.8)
						Temps pour ce modèle : 1.0 min 8.0 secondes.
		On commence par une convolution : True
			Sup : False
				end : False
				De 80% à 140% : 516 sur 2213
			

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Temps pour cette fonction : 5.0 min 1.0 secondes.


Fonction d'activation : tanh

	La première est RELU : True
		On commence par une convolution : False
			Sup : False
				end : False
				De 80% à 140% : 611 sur 2213
						(MAE, MSE, pourc_ok) = (0.5147584415692501, 0.4857148881511584, 27.6)
						Temps pour ce modèle : 0.0 min 14.0 secondes.
				end : True
				De 80% à 140% : 644 sur 2213
						(MAE, MSE, pourc_ok) = (0.45478361636267156, 0.4019708014922162, 29.1)
						Temps pour ce modèle : 0.0 min 27.0 secondes.
			Sup : True
				end : False
				De 80% à 140% : 606 sur 2213
						(MAE, MSE, pourc_ok) = (0.5298409545305294, 0.5107308566087784, 27.4)
						Temps pour ce modèle : 0.0 min 43.0 secondes.
				end : True
				De 80% à 140% : 661 sur 2213
						(MAE, MSE, pourc_ok) = (0.44746771039384464, 0.39408843816377054, 29.9)
						Temps pour ce modèle : 0.0 min 58.0 secondes.
		On commence par une convolution : True
			Sup : False
				end : False
				De 80% à 140% : 628 sur 2213
				

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Temps pour cette fonction : 4.0 min 53.0 secondes.


Fonction d'activation : softplus

	La première est RELU : True
		On commence par une convolution : False
			Sup : False
				end : False
				De 80% à 140% : 612 sur 2213
						(MAE, MSE, pourc_ok) = (0.34020725386792655, 0.24020917676700865, 27.7)
						Temps pour ce modèle : 0.0 min 14.0 secondes.
				end : True
				De 80% à 140% : 583 sur 2213
						(MAE, MSE, pourc_ok) = (0.3454476038701845, 0.2438064750619655, 26.3)
						Temps pour ce modèle : 0.0 min 27.0 secondes.
			Sup : True
				end : False
				De 80% à 140% : 516 sur 2213
						(MAE, MSE, pourc_ok) = (0.37360578911593223, 0.29038647696847153, 23.3)
						Temps pour ce modèle : 0.0 min 42.0 secondes.
				end : True
				De 80% à 140% : 666 sur 2213
						(MAE, MSE, pourc_ok) = (0.3498134186118343, 0.24815586525509753, 30.1)
						Temps pour ce modèle : 0.0 min 57.0 secondes.
		On commence par une convolution : True
			Sup : False
				end : False
				De 80% à 140% : 555 sur 22

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Temps pour cette fonction : 4.0 min 57.0 secondes.


Fonction d'activation : selu

	La première est RELU : True
		On commence par une convolution : False
			Sup : False
				end : False
				De 80% à 140% : 760 sur 2213
						(MAE, MSE, pourc_ok) = (0.35446201962049423, 0.26077705209548113, 34.3)
						Temps pour ce modèle : 0.0 min 13.0 secondes.
				end : True
				De 80% à 140% : 753 sur 2213
						(MAE, MSE, pourc_ok) = (0.361152521536033, 0.25920175250649247, 34.0)
						Temps pour ce modèle : 0.0 min 26.0 secondes.
			Sup : True
				end : False
				De 80% à 140% : 771 sur 2213
						(MAE, MSE, pourc_ok) = (0.3582196772957461, 0.25470815695171245, 34.8)
						Temps pour ce modèle : 0.0 min 42.0 secondes.
				end : True
				De 80% à 140% : 755 sur 2213
						(MAE, MSE, pourc_ok) = (0.368635467294094, 0.27042910628362776, 34.1)
						Temps pour ce modèle : 0.0 min 57.0 secondes.
		On commence par une convolution : True
			Sup : False
				end : False
				De 80% à 140% : 799 sur 2213
			

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Temps pour cette fonction : 4.0 min 45.0 secondes.


Fonction d'activation : elu

	La première est RELU : True
		On commence par une convolution : False
			Sup : False
				end : False
				De 80% à 140% : 787 sur 2213
						(MAE, MSE, pourc_ok) = (0.3378890585278054, 0.2345311885735205, 35.6)
						Temps pour ce modèle : 0.0 min 14.0 secondes.
				end : True
				De 80% à 140% : 728 sur 2213
						(MAE, MSE, pourc_ok) = (0.3383434174359019, 0.2359220547736104, 32.9)
						Temps pour ce modèle : 0.0 min 27.0 secondes.
			Sup : True
				end : False
				De 80% à 140% : 672 sur 2213
						(MAE, MSE, pourc_ok) = (0.3565956317916158, 0.2684643122192804, 30.4)
						Temps pour ce modèle : 0.0 min 42.0 secondes.
				end : True
				De 80% à 140% : 666 sur 2213
						(MAE, MSE, pourc_ok) = (0.3527938280479253, 0.25134059619955385, 30.1)
						Temps pour ce modèle : 0.0 min 57.0 secondes.
		On commence par une convolution : True
			Sup : False
				end : False
				De 80% à 140% : 786 sur 2213
						

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Temps pour cette fonction : 4.0 min 59.0 secondes.


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

#### Les résultats :

In [ ]:
# AVEC deux nouvelles fonctionnalité + Scale loi normale
df_result_1_0_e = df_resultats.sort_values('MSE', ascending = True).copy()
df_result_1_0_e.head(10)

fonc_act  first   Conv    end    sup       MAE       MSE  pourc_ok
60  softplus  False   True  False  False  0.329237  0.222531      28.9
93       elu  False   True   True  False  0.330602  0.224416      36.2
85       elu   True   True   True  False  0.327781  0.226558      33.0
58  softplus  False  False  False   True  0.338660  0.226590      28.2
87       elu   True   True   True   True  0.329850  0.229447      31.8
91       elu  False  False   True   True  0.331343  0.231181      34.9
95       elu  False   True   True   True  0.331530  0.232538      33.4
80       elu   True  False  False  False  0.337889  0.234531      35.6
81       elu   True  False   True  False  0.338343  0.235922      32.9
89       elu  False  False   True  False  0.331631  0.236000      31.8

# Choix d'une méthode

In [ ]:
 	  fonc_act 	first 	Conv 	end 	  sup 	  MAE 	      MSE 	  pourc_ok
60 	softplus 	False 	True 	False 	False 	0.329237 	0.222531 	28.9
93 	elu 	    False 	True 	True 	  False 	0.330602 	0.224416 	36.2
85 	elu 	    True 	  True 	True 	  False 	0.327781 	0.226558 	33.0
58 	softplus 	False 	False False 	True 	  0.338660 	0.226590 	28.2
87 	elu 	    True 	  True 	True 	  True 	  0.329850 	0.229447 	31.8
91 	elu 	    False 	False True 	  True 	  0.331343 	0.231181 	34.9

# Entrainement du modele sur les données complètes

### Récupération, concaténation et traitement des données d'entrainement

In [ ]:
from sklearn.preprocessing import scale


# On regroupe les données 'train' et 'valid'
df_train_final = pd.concat((df_train, df_valid), axis=0, ignore_index=True)
print(df_train.shape)
print(df_valid.shape)
print(df_train_final.shape)

# on split les données pour prédir la zone 1 et la zone 2 :
colonnes_unique_1 = ['t_surge1_input', 't_surge1_output']+[f'surge1_input_{k}' for k in range(10)]
colonnes_unique_2 = ['t_surge2_input', 't_surge1_output']+[f'surge2_input_{k}' for k in range(10)]

X_train_1_final = df_train_final[df_train_final.columns.difference(colonnes_unique_2)]
X_train_2_final = df_train_final[df_train_final.columns.difference(colonnes_unique_1)]


# Normalisation de la sortie avec MinMaxScaler
from sklearn.preprocessing import MinMaxScaler, StandardScaler
norm_entree_1 = StandardScaler()
norm_entree_2 = StandardScaler()

X_train_1_final_scale = norm_entree_1.fit_transform(X_train_1_final)
X_train_2_final_scale = norm_entree_2.fit_transform(X_train_2_final)


# On concatène également les données de sortie y_train et y_valid
for j in range(1,3):
    for k in range(10):
        exec(f"Y_train_{j}_{k}_final = np.concatenate((Y_train_{j}_{k}, Y_valid_{j}_{k}))")

print("On vérifie que la concaténation a bien 5599 valeurs :", len(Y_train_1_0_final) == 5599)

print(len(Y_train_1_0_final))


df_train_final_scale

(3386, 1125)
(2213, 1125)
(5599, 1125)
On vérifie que la concaténation a bien 5599 valeurs : True
5599


array([[-1.55151171,  0.78239224,  1.24626942, ...,         nan,
                nan,         nan],
       [-1.55134326, -0.36765732,  0.12151765, ...,         nan,
                nan,         nan],
       [-1.55119353, -0.89872568, -0.26493191, ...,         nan,
                nan,         nan],
       ...,
       [ 1.77370123, -0.58294543,         nan, ...,  0.53917322,
         0.43336057,  0.25566232],
       [ 1.77385096,  0.13762353,         nan, ..., -0.43522231,
        -0.07408483,  0.19266809],
       [ 1.77401924,  0.63639156,         nan, ..., -1.85457859,
        -1.92714827, -1.76649947]])

### Traitement des données de test :

In [ ]:
# recuperer les données de test nettoyées :
df_train_final

t_slp_begin  slp0_x_0_y_0  slp0_x_0_y_4  slp0_x_0_y_8  slp0_x_0_y_12  \
0    -6.308928e+08      1.017251      1.019911      1.021260       1.021208   
1    -6.308064e+08      1.014756      1.017956      1.020477       1.020881   
2    -6.307200e+08      1.011215      1.013787      1.017968       1.019858   
3    -6.306228e+08      1.004607      1.004016      1.004701       1.009063   
4    -6.283872e+08      1.027163      1.026429      1.025337       1.023838   
...            ...           ...           ...           ...            ...   
5594  1.286950e+09      1.016182      1.013434      1.011187       1.010340   
5595  1.287036e+09      1.014420      1.011629      1.009664       1.011023   
5596  1.287392e+09      1.011767      1.012637      1.014396       1.015555   
5597  1.287565e+09      1.016591      1.016127      1.016357       1.016767   
5598  1.287652e+09      1.018808      1.017131      1.016581       1.017201   

      slp0_x_0_y_16  slp0_x_0_y_20  slp0_x_0_y_24  slp0_x_0_y_28  \
0          1.019921       1.018681       1.018545       1.017563   
1          1.019801       1.019044       1.018436       1.017728   
2          1.020021       1.019869       1.019770       1.019589   
3          1.013247       1.016639       1.019374       1.020586   
4          1.021591       1.020052       1.019101       1.019013   
...             ...            ...            ...            ...   
5594       1.009753       1.009261       1.007498       1.006914   
5595       1.011857       1.011676       1.011139       1.011191   
5596       1.015699       1.014955       1.015204       1.015975   
5597       1.015610       1.014185       1.013894       1.015228   
5598       1.016651       1.015574       1.016440       1.017401   

      slp0_x_0_y_32  ...  surge2_input_2  surge2_input_3  surge2_input_4  \
0          1.015939  ...       -0.757999       -0.129327       -0.179620   
1          1.015910  ...       -0.179620       -0.372413       -0.053886   
2          1.018909  ...       -0.053886        0.356847        0.348464   
3          1.020860  ...        0.348464        0.264641        0.901696   
4          1.018847  ...        0.675374        0.951990        1.371104   
...             ...  ...             ...             ...             ...   
5594       1.006798  ...        1.136400        0.692138        0.784344   
5595       1.011575  ...        0.784344        0.817873        0.734050   
5596       1.015615  ...        0.021555        0.625080        0.390376   
5597       1.017085  ...        0.281406        0.432287        0.155671   
5598       1.018641  ...        0.155671        0.247877        0.415523   

      surge2_input_5  surge2_input_6  surge2_input_7  surge2_input_8  \
0          -0.372413       -0.053886        0.356847        0.348464   
1           0.356847        0.348464        0.264641        0.901696   
2           0.264641        0.901696        0.449052        0.113760   
3           0.449052        0.113760       -0.422707       -0.456236   
4           1.823748        1.278899        0.910078        3.005652   
...              ...             ...             ...             ...   
5594        0.817873        0.734050        0.943607        0.759197   
5595        0.943607        0.759197        0.222730        0.071849   
5596        0.457434        0.281406        0.432287        0.155671   
5597        0.247877        0.415523        0.541257        0.759197   
5598        0.541257        0.759197        0.884931        0.298171   

      surge2_input_9  t_surge1_output  t_surge2_output  
0           0.264641    -6.304860e+08    -6.304824e+08  
1           0.449052    -6.303996e+08    -6.303924e+08  
2          -0.422707    -6.303096e+08    -6.303024e+08  
3          -0.825057    -6.302196e+08    -6.302124e+08  
4           1.521986    -6.279804e+08    -6.279768e+08  
...              ...              ...              ...  
5594        0.222730     1.287353e+09     1.287360e+09  
5595   

In [ ]:
dossier = '/content/drive/MyDrive/M2 DS/DataChallenge/'

df_test = pd.read_csv(dossier+'export_X_test.csv',  index_col=0)

# Séparation des données en deux pour la prévision de chacune des villes

# Création des variables d'entrées X pour chacune des villes 1 et 2:
colonnes_unique_1 = ['t_surge1_input', 't_surge1_output']+[f'surge1_input_{k}' for k in range(10)]
colonnes_unique_2 = ['t_surge2_input', 't_surge1_output']+[f'surge2_input_{k}' for k in range(10)]

X_test_1 = df_test[df_test.columns.difference(colonnes_unique_2)]
X_test_2 = df_test[df_test.columns.difference(colonnes_unique_1)]

X_test_1

slp0_x_0_y_0  slp0_x_0_y_12  slp0_x_0_y_16  slp0_x_0_y_20  slp0_x_0_y_24  \
0        1.017835       1.026203       1.025476       1.025013       1.024426   
1        1.011560       1.016146       1.020164       1.022588       1.026099   
2        1.020676       1.013354       1.013195       1.012694       1.008215   
3        1.022750       1.018441       1.017324       1.016122       1.012993   
4        1.022962       1.018532       1.015485       1.012762       1.012133   
..            ...            ...            ...            ...            ...   
504      1.021540       1.017106       1.015293       1.012063       1.006418   
505      1.023951       1.016154       1.014148       1.013624       1.012502   
506      1.023059       1.015311       1.011936       1.011493       1.012998   
507      1.019511       1.015659       1.013194       1.012229       1.013420   
508      1.019565       1.018927       1.018305       1.019304       1.021665   

     slp0_x_0_y_28  slp0_x_0_y_32  slp0_x_0_y_36  slp0_x_0_y_4  slp0_x_0_y_8  \
0         1.024164       1.024116       1.024296      1.022941      1.025634   
1         1.027211       1.027285       1.025294      1.009317      1.011713   
2         1.008183       1.008829       1.010507      1.018611      1.015836   
3         1.011583       1.012398       1.013018      1.021195      1.019712   
4         1.011634       1.011273       1.010955      1.022200      1.020747   
..             ...            ...            ...           ...           ...   
504       1.004594       1.004460       1.005364      1.020199      1.018713   
505       1.011065       1.010669       1.011360      1.022299      1.019629   
506       1.012468       1.012318       1.012713      1.020784      1.018158   
507       1.013796       1.014927       1.015174      1.018675      1.017325   
508       1.022382       1.022953       1.022993      1.019551      1.019341   

     ...  surge1_input_3  surge1_input_4  surge1_input_5  surge1_input_6  \
0    ...       -1.367103       -1.658701       -1.772659       -2.077663   
1    ...        0.382482        0.134457        0.141160       -0.572751   
2    ...       -0.039831        0.141160        0.352317        0.211546   
3    ...        0.355669        0.184732        0.040609        0.493088   
4    ...       -0.887811       -1.169353       -0.639785       -0.408518   
..   ...             ...             ...             ...             ...   
504  ...        1.384640        1.475136        1.207000        0.503143   
505  ...        0.999195        0.657322        0.231656        0.556771   
506  ...        0.007092        0.650618        0.828258        0.878534   
507  ...        0.684135        0.298690        0.767927        0.908699   
508  ...        0.070775        0.888589        1.545521        1.166779   

     surge1_input_7  surge1_input_8  surge1_input_9   t_slp_begin  \
0         -2.007277       -1.484413       -1.296718 -6.297696e+08   
1         -0.435332       -0.147086       -0.338132 -6.270804e+08   
2         -0.267747       -0.338132       -0.264395 -6.190776e+08   
3         -0.046535       -0.026425       -0.244285 -6.167988e+08   
4         -0.693412       -0.914624        0.040609 -6.145200e+08   
..              ...             ...             ...           ...   
504        0.369076        0.389186        0.305393  1.276171e+09   
505        0.335559        0.033906        0.161270  1.278450e+09   
506        0.952271        0.345614        0.154567  1.280729e+09   
507        0.291987        0.898644        1.150021  1.285967e+09   
508        0.653970        0.409296        0.137809  1.288246e+09   

     t_surge1_input  t_surge2_output  
0     -6.297660e+08    -6.293160e+08  
1     -6.270840e+08    -6.266376e+08  
2     -6.190848e+08    -6.186312e+08  
3     -6.168024e+08    -6.163524e+08  
4     -6.145236e+08    -6.140700e+08  
..              ...              ...  
504    1.276171e+09     1.276625e+09  
505    1.278446e+

In [ ]:
# On scale par rapport au données d'entrainement
X_test_1_scale = norm_entree_1.transform(X_test_1)
X_test_2_scale = norm_entree_2.transform(X_test_2)

In [ ]:
Y_train_1_0_final
X_train_1_final_scale

array([[-0.89872568,  0.54097611,  0.728179  , ..., -1.55119353,
        -1.55118657, -1.55119985],
       [-1.40487896,  0.46406973,  0.69807708, ..., -1.55104379,
        -1.55103684, -1.55104387],
       [-2.12339872,  0.22271435,  0.7534323 , ..., -1.55089406,
        -1.55088086, -1.5508879 ],
       ...,
       [-2.01146351, -0.79213858, -0.33801507, ...,  1.77325203,
         1.7732535 ,  1.77324594],
       [-1.03273547, -0.50616288, -0.36038949, ...,  1.7735515 ,
         1.77356544,  1.77355182],
       [-0.58294543, -0.40397479, -0.09757846, ...,  1.77370123,
         1.77371517,  1.77370762]])

## Entrairement des modèles, prédiction et export des y_test

In [ ]:
""" DERNIERE
60 	softplus 	False 	True 	False 	False 	0.329237 	0.222531 	28.9
93 	elu 	    False 	True 	True 	  False 	0.330602 	0.224416 	36.2
#85 	elu 	    True 	  True 	True 	  False 	0.327781 	0.226558 	33.0
#58 	softplus 	False 	False False 	True 	  0.338660 	0.226590 	28.2
"""

In [ ]:
6108-5600+1

509

In [ ]:
# Boucle pour obtenir toutes les prévisions concernant la première ville (surge1_txx)

dossier_sortie_RN = '/content/drive/MyDrive/M2 DS/DataChallenge/sortieRN/'


# on choisit les modèle suivant :
#fonc_act, first, Conv, end, sup  = 'softplus', False, True, False, False
#fonc_act, first, Conv, end, sup  = 'elu', False, True, True, False
fonc_act, first, Conv, end, sup  = 'elu', True, True, True, False
#58 	softplus 	False 	False False 	True 	  0.338660 	0.226590 	28.2


Modeles_1_et_2 = []
df_sortie = pd.DataFrame(index=range(5600,5600+509))

t0 = time.time()

for j in range(1,3):

    for k in range(10):
        t1 = time.time()
        
        print(f"Entrainement du modèle pour prédir surge{j}_t{k} (Y_test_{j}_{k}) :")

        # entrainement du modèle
        mon_modele_rn = un_model_sequentiel(first_relu = first,
                                                  FONCT_ACT = fonc_act,
                                                  avec_conv = Conv,
                                                  mon_batch=32,
                                                  df = eval(f"X_train_{j}_final_scale"),
                                                  y_true = eval(f"Y_train_{j}_{k}_final"),
                                                  end=end,
                                                  sup=sup )

        Modeles_1_et_2.append(mon_modele_rn)
        print(f"fin de l'entrainement {k}. Durée : {round((time.time()-t1)/60, 1)} minutes.")

        # prédiction de X_test_x
        Y_pred = mon_modele_rn.predict(eval(f"X_test_{j}_scale"))

        # ajout des résultats au df de sortie
        df_sortie[f'surge{j}_t{k}'] = Y_pred

        # Archivage temporaire
        df_sortie.to_csv(dossier_sortie_RN+f'df_sortie_etape_{k}_temp.csv')
    
# Export des résultats    
df_sortie.to_csv(dossier_sortie_RN+'df_sortie_final_test4.csv')

print("Terminée. Durée totale :", round((time.time()-t0)/60, 1), 'minutes.')


Entrainement du modèle pour prédir surge1_t0 (Y_test_1_0) :
fin de l'entrainement 0. Durée : 0.7 minutes.
16/16 [==============================] - 1s 2ms/step
Entrainement du modèle pour prédir surge1_t1 (Y_test_1_1) :
fin de l'entrainement 1. Durée : 0.5 minutes.
16/16 [==============================] - 0s 2ms/step
Entrainement du modèle pour prédir surge1_t2 (Y_test_1_2) :
fin de l'entrainement 2. Durée : 0.7 minutes.
16/16 [==============================] - 0s 2ms/step
Entrainement du modèle pour prédir surge1_t3 (Y_test_1_3) :
fin de l'entrainement 3. Durée : 0.7 minutes.
16/16 [==============================] - 0s 2ms/step
Entrainement du modèle pour prédir surge1_t4 (Y_test_1_4) :
fin de l'entrainement 4. Durée : 0.5 minutes.
16/16 [==============================] - 0s 2ms/step
Entrainement du modèle pour prédir surge1_t5 (Y_test_1_5) :
fin de l'entrainement 5. Durée : 0.5 minutes.
16/16 [==============================] - 0s 3ms/step
Entrainement du modèle pour prédir surge1_t6 (

In [ ]:
df_sortie

surge1_t0  surge1_t1  surge1_t2  surge1_t3  surge1_t4  surge1_t5  \
5600  -1.660706  -1.100623  -1.190051  -0.996848  -1.110946  -0.735122   
5601  -0.155946  -0.383024   0.191348   0.309658   0.383672  -0.107358   
5602  -0.403187  -0.391776  -0.317431  -0.160112  -0.134917  -0.423857   
5603  -0.126878  -0.164678  -0.026621  -0.003880   0.040641  -0.061192   
5604  -0.164904  -0.031323   0.043855   0.118728   0.042263   0.000464   
...         ...        ...        ...        ...        ...        ...   
6104  -0.268929  -0.456797  -0.384407  -0.199284  -0.049625  -0.277972   
6105   0.015506   0.246779   0.421260   0.050487  -0.269287   0.034816   
6106  -0.036774   0.116525   0.069395  -0.012015  -0.056898  -0.132933   
6107   0.935105   1.021880   0.977844   0.797461   0.740962   0.527862   
6108   0.024104   0.028893   1.353777   1.190340   1.012701   0.734239   

      surge1_t6  surge1_t7  surge1_t8  surge1_t9  surge2_t0  surge2_t1  \
5600  -0.520079  -0.399914  -0.358819  -0.405449  -0.740985  -0.721326   
5601  -0.243960   0.124055   0.281573   0.005544   0.262859   0.294231   
5602  -0.380454  -0.324079  -0.352442  -0.217452   0.355437   0.365894   
5603  -0.214207  -0.163736  -0.137344  -0.241221   0.735081   0.838210   
5604  -0.211746  -0.028558  -0.098164  -0.099906  -0.122910  -0.232647   
...         ...        ...        ...        ...        ...        ...   
6104  -0.052610  -0.333135  -0.128262  -0.276424   0.921609   0.742381   
6105   0.047233  -0.030449   0.105903   0.144548   0.814822   0.938380   
6106  -0.092401  -0.253175  -0.173183  -0.273366   0.823730   0.764459   
6107   0.335023   0.673618   0.523473   0.828858   1.479840   1.482681   
6108   0.666915   0.538544   0.543079   0.236439   0.780640   0.486195   

      surge2_t2  surge2_t3  surge2_t4  surge2_t5  surge2_t6  surge2_t7  \
5600  -0.645249  -0.685467  -0.719330  -0.584792  -0.693889  -0.545433   
5601  -0.640063  -0.233278  -0.504718  -0.187205  -0.286132  -0.261144   
5602   0.173969  -0.009038   0.081470  -0.249775  -0.141595  -0.535572   
5603   0.668606   0.518288   0.337695   0.311912   0.136186   0.038152   
5604  -0.192352  -0.126902  -0.392280  -0.239929  -0.457232  -0.388764   
...         ...        ...        ...        ...        ...        ...   
6104   0.821968   0.657151   0.654586   0.732794   0.667758   0.591170   
6105   0.718367   1.034622   0.791355   1.045667   0.795109   0.811449   
6106   0.750035   0.840270   0.665105   0.896786   0.863067   0.864610   
6107   1.004277   1.292508   1.108485   1.369716   1.167561   0.717939   
6108   0.439285   0.719105   0.583338   0.845927   0.805841   0.463110   

      surge2_t8  surge2_t9  
5600  -0.571398  -0.531747  
5601  -0.517483  -0.518558  
5602  -0.518545  -0.513361  
5603   0.011460  -0.038726  
5604  -0.320320  -0.384891  
...         ...        ...  
6104   0.660836   0.537493  
6105   0.714833   0.849526  
6106   0.866160   0.816784  
6107   1.051751   1.113719  
6108   0.346847   0.479620  

[509 rows x 20 columns]

In [ ]:
#dir(mon_modele_rn)
mon_modele_rn.summary()

Model: "sequential_293"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_188 (Conv1D)         (None, 1111, 32)          128       
                                                                 
 batch_normalization_1755 (B  (None, 1111, 32)         128       
 atchNormalization)                                              
                                                                 
 max_pooling1d_188 (MaxPooli  (None, 555, 32)          0         
 ng1D)                                                           
                                                                 
 dropout_1755 (Dropout)      (None, 555, 32)           0         
                                                                 
 flatten_188 (Flatten)       (None, 17760)             0         
                                                                 
 dense_1860 (Dense)          (None, 512)            

# BONUS : Ce que ferait ChatGPT :

La question :

Ecoute moi bien par ce que là je compte sur toi, même si c'est vrai que c'est un peu tard :
J'ai un df dont les 5599 lignes représentent des observations, et les 1125 colonnes sont réparti ainsi :
les 1100 premières sont les pixels de 11 images (flatten) et les 25 dernières colonnes sont d'autres variables explicatives. Je cherche à prédir une variable quantitative centrée normée. Peux-tu utiliser un réseaux de convolution sur les images puis une autre méthode sur les dernières colonnes et concaténer le tout ?

In [ ]:
from keras.layers import Input, Concatenate, Conv2D, Dense, Dropout, Flatten
from keras.models import Model

# définir les entrées pour les images et les autres variables explicatives
img_input = Input(shape=(height, width, n_channels)) # remplacez height, width, et n_channels par les dimensions de vos images
other_input = Input(shape=(25,))

# définir un réseau de convolution pour extraire les caractéristiques des images
conv_layer = Conv2D(32, kernel_size=(3, 3), activation='relu')(img_input)
flatten_layer = Flatten()(conv_layer)

# concaténer les caractéristiques extraites avec les autres variables explicatives
concat_layer = Concatenate()([flatten_layer, other_input])

# Ajoutez des couches de neurones supplémentaires
dense_layer1 = Dense(64, activation='relu')(concat_layer)
dropout_layer1 = Dropout(0.5)(dense_layer1)
dense_layer2 = Dense(32, activation='relu')(dropout_layer1)
dropout_layer2 = Dropout(0.5)(dense_layer2)

# définir une couche dense pour faire la prédiction
output_layer = Dense(1, activation='linear')(dropout_layer2)

# créer le modèle en spécifiant les entrées et la sortie
model = Model(inputs=[img_input, other_input], outputs=output_layer)

# compiler le modèle avec une fonction de coût et un optimiseur
model.compile(loss='mean_squared_error', optimizer='adam')


Son commentaire :
Les couches de neurones supplémentaires peuvent améliorer la capacité de votre modèle à apprendre des relations complexes dans vos données. Les couches Dropout, quant à elles, aident à réduire le surapprentissage en éteignant aléatoirement certaines unités dans les couches de neurones pendant l'entraînement. Il est important de noter que les valeurs de dropout ne sont généralement utilisées qu'au cours de l'entraînement, et non lors de la phase de test ou de production.

Il est important de tester plusieurs configurations différentes et de trouver les meilleurs paramètres pour votre cas d'utilisation spécifique en utilisant des techniques de validation croisée et de mesurer les performances de votre modèle.